### ISSUE TITLE
Join Wahoo?

### ISSUE THREAD

**Issue by bucaran** [0rax/fishline#11]
We are still relatively new in town, and just getting started, but we are more stable than the other options, namely OMF. I think some of these functions could be turned into a handful of Wahoo plugins or maybe some could be even make it to core. We are always accepting feature request and feedback. I would love if you could give [Wahoo](https://github.com/fish-shell/wahoo/blob/master/FAQ.md) a look.

Regards :smile:

**Comment by 0rax** [comment]
Hi @bucaran, thanks for your interest in my project, as we already discuss in #7 I'd prefer if this project stays here as its own. (I like being able to rely on a software individually instead of having part of a frameworky type of things).

Nonetheless as I understand `bucaran/wahoo` is also a package manager, and I will be glad to try and make fishline an installable theme for it.

What are you thought on this ?

**Comment by bucaran** [comment]
Yo! Wahoo has a smaller core and it's fresher take on the whole "framework" for your shell kind of thing. Check out Wahoo and let me know if you would be interested in participating directly with us. Either way, a package for fishline would be very interesting.

**Comment by 0rax** [comment]
Hi @bucaran,

Sorry for the time it take me to take a deeper view on Wahoo, just going through a lot of things @ work and I finally had time to work a little bit more on this project with a v2 coming soon.

Once released, I will take a deeper look on Wahoo and how to make `fishline` a package for it.

**Comment by bucaran** [comment]
@0rax Howdy! Wahoo was deprecated in favor of [Fisherman](https://github.com/fisherman/fisherman), so I think it's safe to close this now! :smile:
