### ISSUE TITLE
Cygwin compatibility

### ISSUE THREAD

**Issue by dutchgecko** [0rax/fishline#13]
Would you consider making your script compatible with cygwin installations? Unfortunately powerline has horrible performance on windows and I'm looking for an alternative.

This is what is currently output after installing fishline:

```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
fish: Unknown command 'tput'
/home/sijpj/.config/fish/fishline/segments/n.fish (line 8):     tput el
                                                                    ^
in function 'FLSEG_N',
        called on line 78 of file '/home/sijpj/.config/fish/fishline/fishline.fish',

in . (source) call of file '-',
        called on line 111 of file '/home/sijpj/.config/fish/fishline/fishline.fish',

in function 'fishline',
        called on line 15 of file '/home/sijpj/.config/fish/config.fish',
        with parameter list '0'

in function 'fish_prompt',
        called on standard input,

in command substitution
        called on standard input,
```

I've tried both the master and dev branches.

**Comment by 0rax** [comment]
Hi, it seems that the only problem you have is that `tput` is not present on Windows.

`tput` was used as a trick in the past for the `N` segment, I need to make some test on how fishline react if this function is removed from this segment.

Making fishline compaitlbe for `cygwin` shouldn't be that hard as I am trying to use a maximum of fish-shell built-in / POSIX command. I will try to make extensive Cygwin testing to make this a reality.

Thanks for your interest on this project.

**Comment by 0rax** [comment]
Some update on this, I was finally able to test this on `Cygwin`.

It seems that since Cygwin 1.7 `tput.exe` has been moved from the `clean` package to the `ncurses` package: see [Cygwin Mailing List](https://www.cygwin.com/ml/cygwin/2009-03/msg00319.html)

You should be able to install `tput` by installing the `ncurses` package.

While testing this on `mintty` I've seen that the first line of my prompt was reprint at pretty much every keystroke. I will try to see if another terminal emulator does the same things and how to avoid it.

By the way, `tput el` is present so that on screen resize we dont have an old part of the prompt still showing.
