### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by ferologics** [0rax/fishline#29]
```
mb@ms-MacBook-Pro ~> fishline
Warning: last status not passed as positional '-s' argument to fishline
fish: Unknown command __fishline_segment_close
~/.config/fish/functions/fishline.fish (line 71): 
    __fishline_segment_close
    ^
in function 'fishline'
	called on standard input

mb@ms-MacBook-Pro ~> 
```

**Comment by ferologics** [comment]
```
mb@ms-MacBook-Pro ~> git clone https://github.com/0rax/fishline.git/ ~/.config/fish/fishline
Cloning into '/Users/mb/.config/fish/fishline'...
remote: Enumerating objects: 1090, done.
remote: Total 1090 (delta 0), reused 0 (delta 0), pack-reused 1090
Receiving objects: 100% (1090/1090), 328.59 KiB | 1.07 MiB/s, done.
Resolving deltas: 100% (696/696), done.
mb@ms-MacBook-Pro ~> vim ~/.config/fish/config.fish
mb@ms-MacBook-Pro ~> fishline
fish: Unknown command fishline
mb@ms-MacBook-Pro ~> fish
source: Error encountered while sourcing file '/Users/mb/.config/fish/conf.d/themes/default_256_colors.fish':
source: No such file or directory
source: Error encountered while sourcing file '/Users/mb/.config/fish/conf.d/themes/default_symbols.fish':
source: No such file or directory
Welcome to fish, the friendly interactive shell
```

**Comment by marnunez** [comment]
Same here.

**Comment by 0rax** [comment]
Hello there, sorry for the late reply it seems that the notifications for this issue got lost in transit.

The issue here seems to arise from this part of the code https://github.com/0rax/fishline/blob/master/init.fish#L23-L32 which makes me think that there might be an issue with your `FLINE_PATH`.

@ferologics in your second example, after updating `config.fish`, you either need to source it (via `source ~/.config/fish/config.fish` or restart fish for your configuration to be taken into account. 

If the issue still exist after that, could you please show me the content of your config.fish at the time of testing as well as the output of `fish --version` and `fishline -v` ?

There might be an issue in how the FLINE_PATH is set, either in your `config.fish` or as it is inferred in `fishline/init.fish`.

Best

**Comment by ferologics** [comment]
@0rax thx 4 the reply. I ended up using the [Tide](https://github.com/IlanCosman/tide) prompt. 🤷‍♂️

**Comment by 0rax** [comment]
Fair enough, `tide` is a pretty good alternative with a more active development. Glad you were able to find something that fits your need.
