### ISSUE TITLE
Terminal Crash on Resize (urxvt)

### ISSUE THREAD

**Issue by UncleDozer** [0rax/fishline#3]
Hello again. I'm running urxvt on AwesomeWM. After installing Fish_Line I get a crash any time I try to resize more than a few pixels.

**Comment by 0rax** [comment]
Sorry for my late awnser.

I've tested fishline and fish in different environement, apparently under `evilvte` (minimal vte term) I can reproduce it but under `Sakura` everything works great.

The error message I get seems to come from fish (it stays on the screen for 1 second before exiting).

Can you check if this is a fishline specific bug or a fish one. Just change you prompt to something like 
`echo $$` and do the same thing.

Thanks for reporting.

**Comment by UncleDozer** [comment]
Definitely a fishline bug. Seems to be related to the "N" segment. I don't have time tonight, but I'll run some tests tomorrow.

**Comment by 0rax** [comment]
I could not reproduce your bug on URXVT/evilvte if the powerline fonts are not loaded, it seems weird, it might be because I am loading the special charactere without their espace sentence (I will change this in the future release).

Also, after checking some of the fish issues I found that you are not the only person to suffer from this and it is a prompt related bug.

If you can make more testing I will be glad to fix it for this prompt.

**Comment by 0rax** [comment]
I reported your problem to the fish-shell project ([here](https://github.com/fish-shell/fish-shell/issues/1529)). It might be fix in the next minor version as shown by the issue.

If you get more info, you can post it here or in the fish project's issue.

Thanks

**Comment by UncleDozer** [comment]
I upgraded to from the stable release of fish to the git version and my issue seems to be resolved.

**Comment by 0rax** [comment]
Glad your bug is fixed.

Issue closed because this is a fish-shell bug.
