### ISSUE TITLE
Support Fisher 4.1.0

### ISSUE THREAD

**Issue by fenprace** [0rax/fishline#33]
Fisher 4.1.0 has been released, which removed `add` and `rm` commands. `add` has been replaced by `install`. The README.md should be updated. See: https://github.com/jorgebucaran/fisher/releases/tag/4.1.0

Also, since 4.0.0, Fisher introduced a new way to organize plugins. All plugin files should be put under `completions`, `conf.d` and `functions` directories. They have deprecated `init.fish` as well. See: https://github.com/jorgebucaran/fisher/releases/tag/4.0.0

Currently, simply running `fisher install 0rax/fishline` will not install fishline successfully.

**Comment by 0rax** [comment]
Thanks for the @fenprace, I just saw #36 which reported the same and sadly it seems that a complete reorganization of how this package works would be needed to restore fisher installation procedure.

I personally do not use `fisher` for any of the "plugins" I use with fish and updating the package to support the new structure would require some changes as well as some trickery to allow users sourcing the original `init.sh` file manually (as I do) not break.

I will think about what can be done here, the original intention of having multiple functions folders loaded as part of the `fish_functions_path` instead of copying them to a user's `~/.config/fish/functions` folder was to keep it clear of "external code".

I feel like there is a way to keep the original `init.sh` file on top of doing things the way `fisher` wants, though I'm not sure how I feel with the need to keep updating my software everytime a big change is done at the package manager level.

**Comment by 0rax** [comment]
I've pushed a new version that should allow everyone to install `fishline` using fisher once again.

I was able to make it work by moving all functions to the `functions` folder, its getting pretty big though that shouldn't be an issue if people do not mind to have that much functions added by a 3rd party. In order to keep shipping multiples themes, I was able to move the bulk part of `init.sh` to `conf.d` and ship a folder called `fishline/themes` there to load what is needed on the fly.

Hope that fixes the issue completely, feel free to bump up this conversation if more work is necessary.
